- id: christmas-lights-on
  alias: Turn on Christmas lights in the evening
  initial_state: on
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: switch.turn_on
    entity_id: group.lights

- id: christmas-lights-off
  alias: Turn off Christmas lights at night
  initial_state: on
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: group.lights

- id: master-bedroom-light-on
  alias: Turn on master bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.master_bedroom_light
    to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: master_bedroom_light_on

- id: master-bedroom-light-off
  alias: Turn off master bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.master_bedroom_light
    to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: master_bedroom_light_off

- id: living-room-light-on
  alias: Turn on living room lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_light
    to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: living_room_light_on

- id: living-room-light-off
  alias: Turn off living room lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_light
    to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: living_room_light_off
      
- id: libby-bedroom-light-on
  alias: Turn on Libby's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.libby_bedroom_light
    to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: libby_bedroom_light_on

- id: libby-bedroom-light-off
  alias: Turn off Libby's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.libby_bedroom_light
    to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: libby_bedroom_light_off
      
- id: carter-bedroom-light-on
  alias: Turn on Carter's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.carter_bedroom_light
    to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: carter_bedroom_light_on

- id: carter-bedroom-light-off
  alias: Turn off Carter's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.carter_bedroom_light
    to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: carter_bedroom_light_off
      
- id: stairway-light-on
  alias: Turn on stairway lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.stairway_light
    to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: stairway_light_on

- id: stairway-light-off
  alias: Turn off stairway lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.stairway_light
    to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: stairway_light_off
