- id: database-purge
  alias: Database Purge
  initial_state: on  
  trigger:
    platform: time
    at: '23:59:59'
  action:
    - service: recorder.purge
      data:
        keep_days: 7
        repack: true

- id: christmas-lights-on
  alias: Turn on Christmas lights in the evening
  initial_state: off
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.smart_switch_2

- id: christmas-lights-off
  alias: Turn off Christmas lights at night
  initial_state: off
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.smart_switch_2
    
- id: porch-lights-on
  alias: Turn on porch lights 15 mins after sunset
  initial_state: on
  trigger:
    platform: sun
    event: sunset
    offset: "00:15:00"
  action:
    service: switch.turn_on
    entity_id: switch.porch_light

- id: porch-lights-off
  alias: Turn off porch lights
  initial_state: on
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.porch_light

- id: backyard-light-on
  alias: Turn on backyard light
  initial_state: on
  trigger:
    platform: time
    at: '19:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.backyard_light

- id: backyard-light-off
  alias: Turn off backyard light
  initial_state: on
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.backyard_light

################
#    Master    #
################
- id: master-bedroom-light-on
  alias: Turn on master bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.master_bedroom_light
    to: 'on'
  action:
   - service: shell_command.master_bedroom_light_toggle
     data:
       token: !secret bond_token

- id: master-bedroom-light-off
  alias: Turn off master bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.master_bedroom_light
    to: 'off'
  action:
    - service: shell_command.master_bedroom_light_toggle
      data:
        token: !secret bond_token

- id: master-bedroom-fan-reverse
  alias: Reverse master bedroom fan
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.master_bedroom_fan_reverse
    to: 'off'
  action:
    - service: shell_command.master_bedroom_fan_reverse
      data:
        token: !secret bond_token

- id: master-bedroom-fan-reverse-reverse
  alias: Reverse reverse master bedroom fan
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.master_bedroom_fan_reverse
    to: 'on'
  action:
    - service: shell_command.master_bedroom_fan_reverse
      data:
        token: !secret bond_token
      
- id: master-bedroom-ceiling-fan-off
  alias: Turn master bedroom ceiling fan to off
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.master_bedroom_fan_speed
    to: "Off"
  action:
  - service: shell_command.master_bedroom_fan_off
    data:
      token: !secret bond_token

- id: master-bedroom-ceiling-fan-low
  alias: Turn master bedroom ceiling fan to low
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.master_bedroom_fan_speed
    to: "Low"
  action:
  - service: shell_command.master_bedroom_fan_low
    data:
      token: !secret bond_token

- id: master-bedroom-ceiling-fan-med
  alias: Turn master bedroom ceiling fan to med
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.master_bedroom_fan_speed
    to: "Medium"
  action:
  - service: shell_command.master_bedroom_fan_med
    data:
      token: !secret bond_token
      
- id: master-bedroom-ceiling-fan-high
  alias: Turn master bedroom ceiling fan to high
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.master_bedroom_fan_speed
    to: "High"
  action:
  - service: shell_command.master_bedroom_fan_high
    data:
      token: !secret bond_token

################
#    Living    #
################
- id: living-room-light-on
  alias: Turn on living room lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_light
    to: 'on'
  action:
  - service: shell_command.living_room_light_toggle
    data:
      token: !secret bond_token

- id: living-room-light-off
  alias: Turn off living room lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_light
    to: 'off'
  action:
  - service: shell_command.living_room_light_toggle
    data:
      token: !secret bond_token

- id: living-room-ceiling-fan-off
  alias: Turn living room ceiling fan to off
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.living_room_fan_speed
    to: "Off"
  action:
  - service: shell_command.living_room_fan_off
    data:
      token: !secret bond_token

- id: living-room-ceiling-fan-low
  alias: Turn living room ceiling fan to low
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.living_room_fan_speed
    to: "Low"
  action:
  - service: shell_command.living_room_fan_low
    data:
      token: !secret bond_token

- id: living-room-ceiling-fan-med
  alias: Turn living room ceiling fan to med
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.living_room_fan_speed
    to: "Medium"
  action:
  - service: shell_command.living_room_fan_med
    data:
      token: !secret bond_token
      
- id: living-room-ceiling-fan-high
  alias: Turn living room ceiling fan to high
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.living_room_fan_speed
    to: "High"
  action:
  - service: shell_command.living_room_fan_high
    data:
      token: !secret bond_token
      
################
#    Libby     #
################
- id: libby-bedroom-light-on
  alias: Turn on Libby's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.libby_bedroom_light
    to: 'on'
  action:
  - service: shell_command.libby_bedroom_light_toggle
    data:
      token: !secret bond_token

- id: libby-bedroom-light-off
  alias: Turn off Libby's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.libby_bedroom_light
    to: 'off'
  action:
  - service: shell_command.libby_bedroom_light_toggle
    data:
      token: !secret bond_token

- id: libby-bedroom-ceiling-fan-off
  alias: Turn Libby's ceiling fan to off
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_bedroom_fan_speed
    to: "Off"
  action:
  - service: shell_command.libby_bedroom_fan_off
    data:
      token: !secret bond_token

- id: libby-bedroom-ceiling-fan-low
  alias: Turn Libby's ceiling fan to low
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_bedroom_fan_speed
    to: "Low"
  action:
  - service: shell_command.libby_bedroom_fan_low
    data:
      token: !secret bond_token

- id: libby-bedroom-ceiling-fan-med
  alias: Turn Libby's ceiling fan to med
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_bedroom_fan_speed
    to: "Medium"
  action:
  - service: shell_command.libby_bedroom_fan_med
    data:
      token: !secret bond_token
      
- id: libby-bedroom-ceiling-fan-high
  alias: Turn Libby's ceiling fan to high
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_bedroom_fan_speed
    to: "High"
  action:
  - service: shell_command.libby_bedroom_fan_high
    data:
      token: !secret bond_token

- id: libby-bedroom-ceiling-fan-reverse
  alias: Reverse direction of Libby's ceiling fan
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.libby_bedroom_fan_reverse
    to: "on"
  action:
  - service: shell_command.libby_bedroom_fan_reverse
    data:
      token: !secret bond_token

- id: libby-bedroom-ceiling-fan-reverse-reverse
  alias: Reverse reverse direction of Libby's ceiling fan
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.libby_bedroom_fan_reverse
    to: "off"
  action:
  - service: shell_command.libby_bedroom_fan_reverse
    data:
      token: !secret bond_token

################
#    Carter    #
################
- id: carter-bedroom-light-on
  alias: Turn on Carter's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.carter_bedroom_light
    to: 'on'
  action:
  - service: shell_command.carter_bedroom_light_toggle
    data:
      token: !secret bond_token

- id: carter-bedroom-light-off
  alias: Turn off Carter's bedroom lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.carter_bedroom_light
    to: 'off'
  action:
  - service: shell_command.carter_bedroom_light_toggle
    data:
      token: !secret bond_token

- id: carter-bedroom-ceiling-fan-off
  alias: Turn Carter's ceiling fan to off
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.carter_bedroom_fan_speed
    to: "Off"
  action:
  - service: shell_command.carter_bedroom_fan_off
    data:
      token: !secret bond_token

- id: carter-bedroom-ceiling-fan-low
  alias: Turn Carter's ceiling fan to low
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.carter_bedroom_fan_speed
    to: "Low"
  action:
  - service: shell_command.carter_bedroom_fan_low
    data:
      token: !secret bond_token

- id: carter-bedroom-ceiling-fan-med
  alias: Turn Carter's ceiling fan to med
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.carter_bedroom_fan_speed
    to: "Medium"
  action:
  - service: shell_command.carter_bedroom_fan_med
    data:
      token: !secret bond_token
      
- id: carter-bedroom-ceiling-fan-high
  alias: Turn Carter's ceiling fan to high
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.carter_bedroom_fan_speed
    to: "High"
  action:
  - service: shell_command.carter_bedroom_fan_high
    data:
      token: !secret bond_token

- id: carter-bedroom-ceiling-fan-reverse
  alias: Reverse direction of Carter's ceiling fan
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.carter_bedroom_fan_reverse
    to: "on"
  action:
  - service: shell_command.carter_bedroom_fan_reverse
    data:
      token: !secret bond_token

- id: carter-bedroom-ceiling-fan-reverse-reverse
  alias: Reverse reverse direction of Carter's ceiling fan
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.carter_bedroom_fan_reverse
    to: "off"
  action:
  - service: shell_command.carter_bedroom_fan_reverse
    data:
      token: !secret bond_token

################
#   Stairway   #
################
- id: stairway-light-on
  alias: Turn on stairway lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.stairway_light
    to: 'on'
  action:
  - service: shell_command.stairway_light_toggle
    data:
      token: !secret bond_token

- id: stairway-light-off
  alias: Turn off stairway lights
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.stairway_light
    to: 'off'
  action:
  - service: shell_command.stairway_light_toggle
    data:
      token: !secret bond_token

- id: stairway-ceiling-fan-off
  alias: Turn stairway ceiling fan to off
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.stairway_fan_speed
    to: "Off"
  action:
  - service: shell_command.stairway_fan_off
    data:
      token: !secret bond_token

- id: stairway-ceiling-fan-low
  alias: Turn stairway ceiling fan to low
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.stairway_fan_speed
    to: "Low"
  action:
  - service: shell_command.stairway_fan_low
    data:
      token: !secret bond_token

- id: stairway-ceiling-fan-med
  alias: Turn stairway ceiling fan to med
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.stairway_fan_speed
    to: "Medium"
  action:
  - service: shell_command.stairway_fan_med
    data:
      token: !secret bond_token
      
- id: stairway-ceiling-fan-high
  alias: Turn stairway ceiling fan to high
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.stairway_fan_speed
    to: "High"
  action:
  - service: shell_command.stairway_fan_high
    data:
      token: !secret bond_token
      
#####################
#   Vacation Mode   #
#####################
- alias: vacation-mode
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
  action:
    service_template: >
      {% if is_state('input_boolean.vacation_mode' , 'on') %} script.turn_on
      {% else %} script.turn_off {% endif %}
    entity_id: script.vacation_mode

#####################
#   Libby LEDs      #
#####################
- id: libby-room-wled-off
  alias: Libby WLED Off
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_room_wled_effects
    to: "Off"
  action:
  - service: shell_command.libby_room_wled_off

- id: libby-room-wled-on
  alias: Libby WLED On
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_room_wled_effects
    to: "On"
  action:
  - service: shell_command.libby_room_wled_on

- id: libby-room-wled-lava-rain
  alias: Libby WLED Lava Rain Theme
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_select.libby_room_wled_effects
    to: "Lava Rain"
  action:
  - service: shell_command.libby_room_wled_lava_rain

#####################
# IOS Notifications #
#####################
- id: test-ios-notification
  alias: Test IOS Notification
  initial_state: off
  trigger:
  - platform: state
    entity_id: switch.smart_switch_1
    to: 'on'
  action:
    service: notify.ios_chans_iphone
    data:
      title: "Smart Alerts"
      message: "Something is happening at home!"

#####################
# Ventilation Fans  #
#####################
- id: ventilation-fan-1-master-bedroom-on
  alias: Turn on Cyclone ventilation fan 1 (master bedroom)
  initial_state: on
  trigger:
  - platform: state
    entity_id: sensor.ecobee_fan_mode
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.TriState_80a9a0_10
    - service: shell_command.master_bedroom_fan_low
      data:
        token: !secret bond_token

- id: ventilation-fan-1-master-bedroom-off
  alias: Turn off Cyclone ventilation fan 1 (master bedroom)
  initial_state: on
  trigger:
  - platform: state
    entity_id: sensor.ecobee_fan_mode
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.TriState_80a9a0_10
    - service: shell_command.master_bedroom_fan_off
      data:
        token: !secret bond_token

