homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto

  # Customization file
  customize: !include customize.yaml

  # Home Assistant Packages
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /home/homeassistant/.homeassistant/dehydrated/certs/chanio.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/dehydrated/certs/chanio.duckdns.org/privkey.pem
  base_url: !secret http_url

# Discover some devices automatically
discovery:

# Lovelace UI Mode
lovelace:
  mode: yaml

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key

# Mosquitto MQTT Broker
mqtt:
  broker: 192.168.1.160
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: chanio

# Sensors
sensor:
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time'
  - platform: template
    sensors:
      dark_outside:
        value_template: "{{ is_state('sun.sun', 'below_horizon') }}"
        friendly_name: "Dark Outside"
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "C"
    value_template: '{{ (value | multiply(0.001)) | round(1) }}'
  - platform: rflink
    automatic_add: true

# Garage Door
cover:
  - platform: mqtt
    name: garage_door
    state_topic: "garage/door"
    command_topic: "garage/button"
    payload_open: "OPEN"
    payload_close: "OPEN"
    payload_stop: "OPEN"
    state_open: "OPENED"
    state_closed: "CLOSED"
    optimistic: false
    retain: false
    value_template: '{{ value }}'

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Unifi Camera
camera:
  - platform: uvc
    nvr: 192.168.1.160
    key: !secret unifi_api_key
    password: !secret unifi_camera_password

# Unifi Wireless AC
device_tracker:
  - platform: unifi
    host: 192.168.1.160
    username: !secret unifi_controller_username
    password: !secret unifi_controller_password
    verify_ssl: false
    detection_time: 60
    ssid_filter:
      - 'beyoootch'
      - 'beyoootch_5g'
    monitored_conditions:
      - last_seen
      - essid
      - ip

group:
automation: !include automations.yaml
script: !include scripts.yaml

tplink:
  switch:
    - host: 192.168.1.161
    - host: 192.168.1.162

switch:
  - platform: rflink
    automatic_add: true
    devices:
      TriState_80aaa1_10: {}
      TriState_80aaa4_10: {}
      TriState_80aa90_10: {}
      TriState_80aa60_10: {}
      TriState_80a9a0_10: {}

  - platform: mqtt
    name: "Sonoff Switch"
    state_topic: "stat/sonoff/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/sonoff/POWER"
    availability_topic: "tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

# Ceiling fan lights
input_boolean:
  master_bedroom_light:
  master_bedroom_fan_reverse:
  carter_bedroom_light:
  carter_bedroom_fan_reverse:
  libby_bedroom_light:
  libby_bedroom_fan_reverse:
  living_room_light:
  stairway_light:
  vacation_mode:

# Ceiling fan speeds
input_select:
  master_bedroom_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  carter_bedroom_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  libby_bedroom_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  living_room_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  stairway_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'

# Ceiling Fan Speeds
shell_command:
    master_bedroom_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/actions/ToggleLight -X PUT -d {}'
    master_bedroom_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/actions/TurnOff -X PUT -d {}'
    master_bedroom_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/actions/SetSpeed -X PUT -d "{\"argument\": 1}"'
    master_bedroom_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/actions/SetSpeed -X PUT -d "{\"argument\": 2}"'
    master_bedroom_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/actions/SetSpeed -X PUT -d "{\"argument\": 3}"'
    master_bedroom_fan_reverse: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/actions/ToggleDirection -X PUT -d {}'
    carter_bedroom_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/actions/ToggleLight -X PUT -d {}'
    carter_bedroom_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/actions/TurnOff -X PUT -d {}'
    carter_bedroom_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/actions/SetSpeed -X PUT -d "{\"argument\": 1}"'
    carter_bedroom_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/actions/SetSpeed -X PUT -d "{\"argument\": 2}"'
    carter_bedroom_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/actions/SetSpeed -X PUT -d "{\"argument\": 3}"'
    carter_bedroom_fan_reverse: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/actions/ToggleDirection -X PUT -d {}'
    libby_bedroom_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/actions/ToggleLight -X PUT -d {}'
    libby_bedroom_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/actions/TurnOff -X PUT -d {}'
    libby_bedroom_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/actions/SetSpeed -X PUT -d "{\"argument\": 1}"'
    libby_bedroom_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/actions/SetSpeed -X PUT -d "{\"argument\": 2}"'
    libby_bedroom_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/actions/SetSpeed -X PUT -d "{\"argument\": 3}"'
    libby_bedroom_fan_reverse: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/actions/ToggleDirection -X PUT -d {}'
    living_room_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/actions/ToggleLight -X PUT -d {}'
    living_room_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/actions/TurnOff -X PUT -d {}'
    living_room_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/actions/SetSpeed -X PUT -d "{\"argument\": 1}"'
    living_room_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/actions/SetSpeed -X PUT -d "{\"argument\": 2}"'
    living_room_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/actions/SetSpeed -X PUT -d "{\"argument\": 3}"'
    stairway_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/actions/ToggleLight -X PUT -d {}'
    stairway_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/actions/TurnOff -X PUT -d {}'
    stairway_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/actions/SetSpeed -X PUT -d "{\"argument\": 1}"'
    stairway_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/actions/SetSpeed -X PUT -d "{\"argument\": 2}"'
    stairway_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/actions/SetSpeed -X PUT -d "{\"argument\": 3}"'

# RGB strip lights
light:
  - platform: mqtt
    name: "RGB1"
    state_topic: "stat/sonoffrgb1/RESULT"
    command_topic: "cmnd/sonoffrgb1/POWER"
    state_value_template: "{{ value_json.POWER }}"
    brightness_state_topic: "stat/sonoffrgb1/RESULT"
    brightness_command_topic: "cmnd/sonoffrgb1/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{ value_json.Dimmer }}"
    white_value_state_topic: "stat/sonoffrgb1/RESULT"
    white_value_command_topic: "cmnd/sonoffrgb1/Channel4"
    white_value_scale: 100
    white_value_template: "{{ value_json.Channel[3] }}"
    rgb_state_topic: "stat/sonoffrgb1/RESULT"
    rgb_command_topic: "cmnd/sonoffrgb1/Color"
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_value_template: "{{(value_json.Channel[0]*2.55)|int}},{{(value_json.Channel[1]*2.55)|int}},{{(value_json.Channel[2]*2.55)|int}}"
    effect_state_topic: "stat/sonoffrgb1/RESULT"
    effect_command_topic: "cmnd/sonoffrgb1/Scheme"
    effect_value_template: "{{ value_json.Scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
    
  - platform: mqtt
    name: "RGB2"
    state_topic: "stat/sonoffrgb2/RESULT"
    command_topic: "cmnd/sonoffrgb2/POWER"
    state_value_template: "{{ value_json.POWER }}"
    brightness_state_topic: "stat/sonoffrgb2/RESULT"
    brightness_command_topic: "cmnd/sonoffrgb2/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{ value_json.Dimmer }}"
    white_value_state_topic: "stat/sonoffrgb2/RESULT"
    white_value_command_topic: "cmnd/sonoffrgb2/Channel4"
    white_value_scale: 100
    white_value_template: "{{ value_json.Channel[3] }}"
    rgb_state_topic: "stat/sonoffrgb2/RESULT"
    rgb_command_topic: "cmnd/sonoffrgb2/Color"
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_value_template: "{{(value_json.Channel[0]*2.55)|int}},{{(value_json.Channel[1]*2.55)|int}},{{(value_json.Channel[2]*2.55)|int}}"
    effect_state_topic: "stat/sonoffrgb2/RESULT"
    effect_command_topic: "cmnd/sonoffrgb2/Scheme"
    effect_value_template: "{{ value_json.Scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
  
  - platform: rflink
    automatic_add: true

rflink:
#  host: 192.168.1.181
#  port: 2323
  port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0


# IOS Notifications
ios:

