homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto

  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /home/homeassistant/.homeassistant/dehydrated/certs/chanio.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/dehydrated/certs/chanio.duckdns.org/privkey.pem
  base_url: !secret http_url

# Discover some devices automatically
discovery:

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key

# Mosquitto MQTT Broker
mqtt:
  broker: 192.168.1.160
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: chanio

# Sensors
sensor:
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time'
  - platform: template
    sensors:
      dark_outside:
        value_template: "{{ is_state('sun.sun', 'below_horizon') }}"
        friendly_name: "Dark Outside"
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "C"
    value_template: '{{ (value | multiply(0.001)) | round(1) }}'
  - platform: rflink
    automatic_add: true

# Garage Door
cover:
  - platform: mqtt
    name: garage_door
    state_topic: "garage/door"
    command_topic: "garage/button"
    payload_open: "OPEN"
    payload_close: "OPEN"
    payload_stop: "OPEN"
    state_open: "OPENED"
    state_closed: "CLOSED"
    optimistic: false
    retain: false
    value_template: '{{ value }}'

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Unifi Camera
camera:
  - platform: uvc
    nvr: 192.168.1.160
    key: !secret unifi_api_key
    password: !secret unifi_camera_password

# Unifi Wireless AC
device_tracker:
  - platform: unifi
    host: 192.168.1.160
    username: !secret unifi_controller_username
    password: !secret unifi_controller_password
    verify_ssl: false
    detection_time: 60
    ssid_filter:
      - 'beyoootch'
      - 'beyoootch_5g'
    monitored_conditions:
      - last_seen
      - essid
      - ip

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

tplink:
  switch:
    - host: 192.168.1.161
    - host: 192.168.1.162

switch:
  - platform: rflink
    automatic_add: true
    devices:
      TriState_80aaa1_10: {}
      TriState_80aaa4_10: {}
      TriState_80aa90_10: {}
      TriState_80aa60_10: {}
      TriState_80a9a0_10: {}

# Ceiling fan lights
input_boolean:
  master_bedroom_light:
  master_bedroom_fan_reverse:
  carter_bedroom_light:
  carter_bedroom_fan_reverse:
  libby_bedroom_light:
  libby_bedroom_fan_reverse:
  living_room_light:
  stairway_light:
  vacation_mode:

# Ceiling fan speeds
input_select:
  master_bedroom_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  carter_bedroom_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  libby_bedroom_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  living_room_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'
  stairway_fan_speed:
    options:
      - 'Off'
      - 'Low'
      - 'Medium'
      - 'High'

# Ceiling Fan Speeds
shell_command:
    master_bedroom_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/commands/00000054/tx -X PUT -d {}'
    master_bedroom_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/commands/00000056/tx -X PUT -d {}'
    master_bedroom_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/commands/0000004e/tx -X PUT -d {}'
    master_bedroom_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/commands/00000050/tx -X PUT -d {}'
    master_bedroom_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/commands/00000052/tx -X PUT -d {}'
    master_bedroom_fan_reverse: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000049/commands/00000058/tx -X PUT -d {}'
    carter_bedroom_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/commands/0000001d/tx -X PUT -d {}'
    carter_bedroom_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/commands/0000001f/tx -X PUT -d {}'
    carter_bedroom_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/commands/00000015/tx -X PUT -d {}'
    carter_bedroom_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/commands/00000019/tx -X PUT -d {}'
    carter_bedroom_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/commands/0000001b/tx -X PUT -d {}'
    carter_bedroom_fan_reverse: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000012/commands/00000021/tx -X PUT -d {}'
    libby_bedroom_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/commands/0000002e/tx -X PUT -d {}'
    libby_bedroom_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/commands/00000030/tx -X PUT -d {}'
    libby_bedroom_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/commands/00000026/tx -X PUT -d {}'
    libby_bedroom_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/commands/0000002a/tx -X PUT -d {}'
    libby_bedroom_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/commands/0000002c/tx -X PUT -d {}'
    libby_bedroom_fan_reverse: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000023/commands/00000032/tx -X PUT -d {}'
    living_room_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/commands/00000006/tx -X PUT -d {}'
    living_room_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/commands/0000000a/tx -X PUT -d {}'
    living_room_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/commands/00000008/tx -X PUT -d {}'
    living_room_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/commands/0000000c/tx -X PUT -d {}'
    living_room_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000003/commands/0000000e/tx -X PUT -d {}'
    stairway_light_toggle: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/commands/0000003f/tx -X PUT -d {}'
    stairway_fan_off: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/commands/00000041/tx -X PUT -d {}'
    stairway_fan_low: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/commands/00000039/tx -X PUT -d {}'
    stairway_fan_med: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/commands/0000003b/tx -X PUT -d {}'
    stairway_fan_high: 'curl -H "BOND-Token: {{ token }}" -i http://192.168.1.165/v2/devices/00000034/commands/0000003d/tx -X PUT -d {}'

# RGB strip lights
light:
  - platform: mqtt
    name: "RGB1"
    state_topic: "stat/sonoffrgb1/RESULT"
    command_topic: "cmnd/sonoffrgb1/POWER"
    state_value_template: "{{ value_json.POWER }}"
    brightness_state_topic: "stat/sonoffrgb1/RESULT"
    brightness_command_topic: "cmnd/sonoffrgb1/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{ value_json.Dimmer }}"
    white_value_state_topic: "stat/sonoffrgb1/RESULT"
    white_value_command_topic: "cmnd/sonoffrgb1/Channel4"
    white_value_scale: 100
    white_value_template: "{{ value_json.Channel[3] }}"
    rgb_state_topic: "stat/sonoffrgb1/RESULT"
    rgb_command_topic: "cmnd/sonoffrgb1/Color"
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_value_template: "{{(value_json.Channel[0]*2.55)|int}},{{(value_json.Channel[1]*2.55)|int}},{{(value_json.Channel[2]*2.55)|int}}"
    effect_state_topic: "stat/sonoffrgb1/RESULT"
    effect_command_topic: "cmnd/sonoffrgb1/Scheme"
    effect_value_template: "{{ value_json.Scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
    
  - platform: mqtt
    name: "RGB2"
    state_topic: "stat/sonoffrgb2/RESULT"
    command_topic: "cmnd/sonoffrgb2/POWER"
    state_value_template: "{{ value_json.POWER }}"
    brightness_state_topic: "stat/sonoffrgb2/RESULT"
    brightness_command_topic: "cmnd/sonoffrgb2/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{ value_json.Dimmer }}"
    white_value_state_topic: "stat/sonoffrgb2/RESULT"
    white_value_command_topic: "cmnd/sonoffrgb2/Channel4"
    white_value_scale: 100
    white_value_template: "{{ value_json.Channel[3] }}"
    rgb_state_topic: "stat/sonoffrgb2/RESULT"
    rgb_command_topic: "cmnd/sonoffrgb2/Color"
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_value_template: "{{(value_json.Channel[0]*2.55)|int}},{{(value_json.Channel[1]*2.55)|int}},{{(value_json.Channel[2]*2.55)|int}}"
    effect_state_topic: "stat/sonoffrgb2/RESULT"
    effect_command_topic: "cmnd/sonoffrgb2/Scheme"
    effect_value_template: "{{ value_json.Scheme }}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
  
  - platform: rflink
    automatic_add: true

rflink:
  port: /dev/ttyUSB0
