homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_password
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key
  
# Unifi Camera
camera:
  - platform: uvc
    nvr: 192.168.1.105
    key: !secret unifi_api_key
    password: !secret unifi_camera_password

# Unifi Wireless AC
device_tracker:
  - platform: unifi
    host: 192.168.1.105
    username: !secret unifi_controller_username
    password: !secret unifi_controller_password
    verify_ssl: false
    detection_time: 60
    ssid_filter:
      - 'beyoootch'
      - 'beyoootch 5G'
    monitored_conditions:
      - last_seen
      - essid
      - ip

weather:
  - platform: yweather
  
switch:
  - platform: tplink
    name: Smart Switch 1
    host: 192.168.1.161
  - platform: tplink
    name: Smart Switch 2
    host: 192.168.1.162
    
ifttt:
  key: !secret ifttt_api_key
  
# Ceiling fan lights
input_boolean:
  master_bedroom_light:
    name: Master Bedroom Lights
  carter_bedroom_light:
    name: Carter's Bedroom Lights    
  libby_bedroom_light:
    name: Libby's Bedroom Lights
  living_room_light:
    name: Living Room Lights
  stairway_light:
    name: Stairway Lights
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
