title: Home
views:
  - path: default_view
    title: Home
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.ecobee_thermostat
      - type: thermostat
        entity: climate.ecobee_thermostat
      - type: entities
        entities:
          - sensor.family_room_temperature
          - sensor.master_bedroom_temperature
          - sensor.ecobee_thermostat_temperature
          - sensor.carters_room_temperature
          - sensor.ecobee_thermostat_humidity
        title: Home Climate
        show_header_toggle: false
      - type: entities
        entities:
          - switch.smart_switch_1
          - switch.smart_switch_2
          - type: divider
          - switch.tristate_80aaa4_10
          - switch.tristate_80aa90_10
          - switch.tristate_80aa60_10
          - switch.tristate_80a9a0_10
        title: Switches
        show_header_toggle: true
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - cover.garage_door
              - switch.tristate_80aaa1_10
              - switch.porch_light
              - switch.backyard_light
            title: Outdoor
            show_header_toggle: false
          - type: picture-entity
            entity: camera.front_yard
          - type: picture-entity
            entity: camera.garage_camera
      - type: entities
        entities:
          - binary_sensor.family_room_occupancy
          - binary_sensor.master_bedroom_occupancy
          - binary_sensor.ecobee_thermostat_occupancy
          - binary_sensor.carters_room_occupancy
        title: Occupancy
        show_header_toggle: false
    icon: 'mdi:home'
  - path: rooms_view
    title: Rooms
    badges: []
    cards:
      - type: entities
        entities:
          - input_boolean.master_bedroom_light
          - input_boolean.master_bedroom_fan_reverse
          - input_select.master_bedroom_fan_speed
        title: Master Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.carter_bedroom_light
          - input_boolean.carter_bedroom_fan_reverse
          - input_select.carter_bedroom_fan_speed
        title: Carter's Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.libby_bedroom_light
          - input_boolean.libby_bedroom_fan_reverse
          - input_select.libby_bedroom_fan_speed
          - light.libby_room_led_lights
        title: Libby's Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.living_room_light
          - input_select.living_room_fan_speed
        title: Living Room
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.stairway_light
          - input_select.stairway_fan_speed
        title: Stairway
        show_header_toggle: false
    icon: 'mdi:fan'
  - path: media_players
    title: Media
    badges: []
    cards:
      - type: media-control
        entity: media_player.family_room_tv
      - type: media-control
        entity: media_player.family_room_speaker
    icon: 'mdi:play-box-outline'
  - path: system_status
    title: System Status
    badges: []
    cards:
      - type: entities
        entities:
          - device_tracker.chansiphone
          - device_tracker.mer
          - device_tracker.mahmah_phone
          - device_tracker.yehyeh_phone
          - device_tracker.yvonnes_phone
          - device_tracker.augustines_phone
        title: People
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.cpu_temperature
          - input_boolean.vacation_mode
          - switch.reboot_garage_camera
          - script.reboot_garage_sensor
        title: System
        show_header_toggle: false
    icon: 'mdi:settings'

