binary_sensor:
  - platform: mqtt
    name: Libby Room HASP Connected
    device_class: connectivity
    state_topic: "hasp/hasp_libby/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/hasp_libby/status"
    payload_available: "ON"
    payload_not_available: "OFF"

